# pod attracts the pod. lets say pod 1 is created in node1 if affinity is set to pod1 , then pod-2 creates in node1 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  namespace: demo
  labels:
    project: demo
    tier: web
    app: frontend
    purpose: affinity-of-nginx-1-pod
spec:
  containers:
  - name: nginx-1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  namespace: demo
  labels:
    project: demo
    tier: web
    app: frontend
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - affinity-of-nginx-1-pod
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx-2
    image: nginx
