apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  namespace: demo
  labels:
    project: demo
    tier: web
    app: frontend
    purpose: affinity-of-nginx-1-pod
spec:
  containers:
  - name: nginx-1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  namespace: demo
  labels:
    project: demo
    tier: web
    app: frontend
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: purpose
              operator: In
              values:
              - affinity-of-nginx-1-pod
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx-1
    image: nginx

